### ISSUE TITLE
Doesn't work with new update, PLUS Suggestion

### ISSUE THREAD

**Issue by joansutherland** [realmayus/anki_forvo_dl#102]
This add-on was soooo useful! but it doesn't work with the new update.. 

would be forever grateful if you could update. 

also... dream request... could there be a multi add option? 

Having multiple audio files is awesome! just selecting once would be a dream. 

You're awesome and I love you...

**Comment by realmayus** [comment]
Fixed with #101.
Batch downloading used to be a feature, but I realized that it got many people banned due to the load of requests.
