### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alvarocarou** [realmayus/anki_forvo_dl#113]
Several users reported the plugin not working on Ankiweb. I couldn't get it to work myself for japanese on Anki 2.1.49

>  dislike on 2024-06-18
> Same problem, it doesn't work anymore. I had the same problem 2 weeks ago, but reinstalling it fixed it, but this time it doesn't solve anything.
> dislike on 2024-06-18
> Today (18-Jun-2024) the add-on appears to have stopped working. When I click the button I just get "No results found! :(" when 
> there are definitely entries in Forvo. I removed and reinstalled the add-on in the hope that would fix it. Any advice?

**Comment by Grrrl77** [comment]
I have the same issue. Tried everything.

**Comment by ecsalamanc** [comment]
Seconded. Stopped working 7/24/2024 (as did others on the Anki review page, which you might not have seen)

**Comment by valerykalashnikov** [comment]
Stopped working. When I try to add audio, get everytime "No results found"

**Comment by OsamaLab** [comment]
#114 should fix this.

**Comment by jarmanso7** [comment]
Not working for me either
