### ISSUE TITLE
Crash after adding first recordings

### ISSUE THREAD

**Issue by ioculus** [realmayus/anki_forvo_dl#15]
I can use the add-on with one or two words but then it stops working. I use it to import Uzbek pronunciation.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-03 10:52:31

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "aqt\editor.py", line 443, in onBridgeCmd
  File "C:\Users\ioann\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 158, in on_editor_btn_click
    proceed(config_lang.value)
  File "C:\Users\ioann\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 91, in proceed
    results = Forvo(query, language, editor.mw) \
  File "C:\Users\ioann\AppData\Roaming\Anki2\addons21\858591644\Forvo.py", line 77, in load_search_query
    self.html = BeautifulSoup(page, "html.parser")
UnboundLocalError: local variable 'page' referenced before assignment

**Comment by realmayus** [comment]
Thanks for the report! I'll look into it ASAP.

**Comment by msspencer2** [comment]
I believe I am also having a similar issue.  I am trying to add Persian pronunciation audio.  When I try I receive a similar error message.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-05 07:54:28
Add-ons possibly involved: ⁨anki-forvo-dl  Forvo Downloader fully automatic with bulk-add mode⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/michaelscottspencerii/Library/Application Support/Anki2/addons21/858591644/__init__.py", line 172, in handle_lang_select
    proceed(d.selected_lang)
  File "/Users/michaelscottspencerii/Library/Application Support/Anki2/addons21/858591644/__init__.py", line 99, in proceed
    raise Exception()
Exception

**Comment by ioculus** [comment]
I believe I found something on that matter. If I leave a space after a word (e.g. when copying it) the add-on might crash. It looks like it doesn't like it at the end or beginning of the word or phrase.

**Comment by msspencer2** [comment]
I double checked and it seems to still give me the same error message

<img width="1154" alt="Screen Shot 2021-04-05 at 2 14 06 PM" src="https://user-images.githubusercontent.com/81996566/113628078-3c015080-9619-11eb-93e4-9a281467ccc0.png">

**Comment by realmayus** [comment]
Oh I'm sorry, I forgot about this issue 😬
@ioculus Are you on the latest version? I think I fixed your crash at some point. Please check if you have any updates:
![image](https://user-images.githubusercontent.com/38134006/113764183-eb721c00-971a-11eb-9571-ed0241a2f170.png)
If it still doesn't work, I'll look into it again 👍 

@msspencer2 It looks like you're experiencing a different issue. I'll have a look at it, thanks for the report! 👍

**Comment by ioculus** [comment]
My version is the up to date one and it works much better, thanks :)

Pozdrawiam

Jan Oko
------------------------------------------------------------
blog: http://ioannesoculus.com/
