### ISSUE TITLE
Documentation on config.json

### ISSUE THREAD

**Issue by CarloMartini** [realmayus/anki_forvo_dl#16]
Hello,
Could the author provide an example on how to change the source/destination field sin the JSON file? Thank you

**Comment by CarloMartini** [comment]
Nevermind... It's obvious once those field have actually been added to the json, that is after the first usage. 
I tried to edit the setting before doing the first bulk download!

**Comment by realmayus** [comment]
Thanks for the report! Nice that you got it to work. You’re right, there should be an easy way to change the field names. I’ll add a config editor GUI soon 👍

**Comment by realmayus** [comment]
Se #7
