### ISSUE TITLE
Prepend the audio string to the existing contents of the audio field

### ISSUE THREAD

**Issue by imjoeyli** [realmayus/anki_forvo_dl#18]
Hi Marius, 

Thank you for making such an easy-to-use plugin!

I have a question: How to set it up to add the audio file to the beginning of the field? (The default is to add to the end of the field).

> By default, anki-forvo-dl will append the audio string to the existing contents of the audio field. If you want to change that, see the "Editing the config" section.

I checked and tried to modify the configuration file, but there doesn't seem to be an option for this.

**Comment by realmayus** [comment]
Thank you for the issue! Currently there isn't a way to do this, but I will add it now, it'll be available in the next update!

**Comment by realmayus** [comment]
This was fixed in cdf7f505d693cab5db188a87dfbdd6137f696a4d. A new release will follow shortly.
