### ISSUE TITLE
Feature request: input box

### ISSUE THREAD

**Issue by rwmpelstilzchen** [realmayus/anki_forvo_dl#20]
Hi,

*Current situation:*
At the moment, if I understand correctly the only way to search for a word using this add-on is to put it as is in a field.

*The problem:*
Sometimes the form that is written in the field doesn’t match the forms that exist on Forvo. Say you learn English and write all infinitives with ‘to’. Your field should have ‘[to celebrate](https://forvo.com/word/to%20celebrate/#en)’, but Forvo has only ‘[celebrate](https://forvo.com/word/celebrate/#en)’.

*Proposed solution:*
The solution I propose is to add the option for users to input an arbitrary string for search. I think it is best if the default value of the search will be the current value of the relevant field, selected. This way the user has a basis to build upon, and it is easy to replace the whole string with something else. This is the behaviour used in browsers when hittin <kbd>ctrl</kbd>+<kbd>L</kdb>.

**Comment by realmayus** [comment]
Thanks for the feature request! I'll add a shortcut that opens a small dialog box with a text box before opening the pronunciation selector.

**Comment by rwmpelstilzchen** [comment]
Thanks! 🙂
