### ISSUE TITLE
Bold, underline blocks finding on Forvo

### ISSUE THREAD

**Issue by bplat** [realmayus/anki_forvo_dl#25]
In my Russian study I use bold or underline to signify which syllable has stress. Forvo_dl takes this string as is apparently, because if any character is bold or underlined Forvo doesn't return any results. 

If possible, clean the input from such marking before offering to Forvo.

**Comment by realmayus** [comment]
This was fixed in 3942fbe48d7704951b81c655889f76961077aa86. A new version will follow soon
