### ISSUE TITLE
[Feature Request] Ignore the brackets and inside contents when searching

### ISSUE THREAD

**Issue by imjoeyli** [realmayus/anki_forvo_dl#27]
Hi Marius,

I am currently learning Japanese and in order to add furigana to kanji, as the pictures shows, I need to add brackets after the kanji as well as enter the kana inside.

Obviously, this makes it impossible to search for pronunciations even if they exist when searching Forvo.

I would like to know if there is currently a way to ignore the brackets and the contents inside when searching?

![20210628133043](https://user-images.githubusercontent.com/48614287/123785101-b7b62500-d90a-11eb-83dc-8676ad5f39be.png)

![20210628132852](https://user-images.githubusercontent.com/48614287/123785105-ba187f00-d90a-11eb-9e33-e246bf4a2c23.jpg)

**Comment by realmayus** [comment]
Hi Joey,
thanks for your comment!
Currently, it's not possible to do this with the plugin.

I'm using the Japanese Language Support addon as well, and I have two fields for the Japanese word: A field called "Expression" and one named "Reading". The Japanese Addon recognizes these names and when you enter 本 in the field named "Expression" it automatically generates the furigana (`本[ほん]`) in the "Reading" field once you unfocus the Expression field.

I'll consider adding that feature, although I'll probably add a toggle in the config to avoid interference. 👍

**Comment by imjoeyli** [comment]
> Hi Joey,
> thanks for your comment!
> Currently, it's not possible to do this with the plugin.
> 
> I'm using the Japanese Language Support addon as well, and I have two fields for the Japanese word: A field called "Expression" and one named "Reading". The Japanese Addon recognizes these names and when you enter 本 in the field named "Expression" it automatically generates the furigana (`本[ほん]`) in the "Reading" field once you unfocus the Expression field.
> If you use that system and select the Expression field in anki-forvo-dl it will contain the "raw" word, without any brackets, which should fix the issue.
> 
> I'll consider adding that feature, although I'll probably add a toggle in the config to avoid interference. 👍

Hi Marius,

Thank you for mentioning this addon, I installed and tried it, it does meet my needs!
