### ISSUE TITLE
Take out white spaces and line breaks (EOL, newline, hard return)

### ISSUE THREAD

**Issue by nitaicharan** [realmayus/anki_forvo_dl#34]
Please consider taking out the white spaces and line breaks from the search field before search the term on Forvo.

Follows an example:

### Wrong form
Text with a line break after the search term

![image](https://user-images.githubusercontent.com/14323599/126548069-051a481f-d181-4649-bf2b-4970af31b7d2.png)

Or just with a white space after or before

![image](https://user-images.githubusercontent.com/14323599/126548534-6672af95-3047-4997-bb34-13c16b1155c4.png)

**Comment by nitaicharan** [comment]
I tried to fix it by myself but looks like there is a different version of this addon on Forvo available to download.

**Comment by realmayus** [comment]
As of the newest version, you can add characters to ignore to the config. Just open the config manager by clicking on Tools>anki-forvo-dl>Preferences and add it there! Alternatively, you can also open the config manually (probably better for adding invisible characters like newlines) and add it there to the string list.
