### ISSUE TITLE
Add option for disabling .ogg fallback

### ISSUE THREAD

**Issue by fightme-cmd** [realmayus/anki_forvo_dl#42]
Sometimes random (my longer?) audio clips auto download as .ogg, if reviewing on the anki ios app these do not play.

Can I force the add on to always download in mp3 or is this on forvo?

**Comment by realmayus** [comment]
The addon always prefers downloading the audio files as mp3s, but sometimes that's not possible and .ogg is used as a fallback. So there's nothing I can do, sorry!

**Comment by fightme-cmd** [comment]
Hm. Could you give us the option to turn off .ogg? To just not download if it can't be mp3?

Cause the ogg is useless and a ends up slowing down the workflow having to delete.

**Comment by realmayus** [comment]
Hm yeah, I'll have a look and leave this open

**Comment by Calvin-Xu** [comment]
> Hm. Could you give us the option to turn off .ogg? To just not download if it can't be mp3?
> 
> Cause the ogg is useless and it ends up slowing down the workflow having to delete.

You can convert all .ogg audio files in the collection.media folder to a codec Anki iOS supports (mp3, aac), then batch search and replace .ogg in your note fields.
