### ISSUE TITLE
Bring back bulk-add dialog with restrictions

### ISSUE THREAD

**Issue by realmayus** [realmayus/anki_forvo_dl#51]
- At least 10 seconds between every pronunciation
- 3 seconds between the scrape request and the audio request

**Comment by it0na72** [comment]
this would make it perfect. up for this

**Comment by Digital-Coder** [comment]
I really miss this feature

**Comment by Digital-Coder** [comment]
maybe user could add forvo api key and use bulk-add without restrictions ? And user without api key could be throttled
