### ISSUE TITLE
Forvo scraping tool to use the add-on offline

### ISSUE THREAD

**Issue by FyTpodQUuWvQNTh** [realmayus/anki_forvo_dl#54]
Hi ! **Recently, a tool to scrape all sounds from Forvo was published :**

https://ankiweb.net/shared/info/858591644#:~:text=a%20method%20to%20scrape%20all%20forvo%20pronunciations

Would it be possible to scrape audios in one's target language and use the add-on without internet connection with "local" files ?

**Comment by realmayus** [comment]
Nope that’s not possible with the addon.
