### ISSUE TITLE
Button doesn't appear and shortcut doesn't work in the QT6 beta of Anki

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [realmayus/anki_forvo_dl#55]
#### Problem description

Dae's [posted a QT6 beta of Anki](https://forums.ankiweb.net/t/new-toolkit-and-packaging-test-round-2/14513). Most of my addons work fine, but unfortunately, that doesn't include anki-forvo-dl.

The blue 'search forvo' button doesn't appear on the "add" interface; and the <kbd>⌃F</kbd> shortcut doesn't function either.

#### Information about your Anki set-up

```
    Anki 2.1.50 (abd671d4) Python 3.9.7 Qt 6.2.0 PyQt 6.2.0
    Platform: Mac 12.0.1
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2021-12-02 08:37:14
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
    ===IDs of active AnkiWeb add-ons===
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by ELLIOTTCABLE** [comment]
It looks like upstream may fix(?) this, or at least might mitigate some of the bugs:

https://github.com/glutanimate/review-heatmap/issues/136#issuecomment-990000408

**Comment by realmayus** [comment]
Should be working now
