### ISSUE TITLE
Some audios wont play on IOS app

### ISSUE THREAD

**Issue by frtoli002** [realmayus/anki_forvo_dl#58]
Hello! Firstly thanks for your great add on. I am not very techy so please excuse me if this is something very simple. I normally make my cards on my laptop then practise on my phone using the iPhone app. Weirdly, a lot of the audio files wont play and this message comes up. Any idea why or how I could fix it? Thanks

![image](https://user-images.githubusercontent.com/100732231/156260842-e82d6528-c756-4ee9-a46d-1a37839f8bdc.png)

**Comment by ohare93** [comment]
Some files on Forvo are ".ogg" format. This is not supported on iOS. You can open the settings for this extension and set it to ignore ".ogg" files in the future. Then they will never be selected or downloaded. You will need to fix all the ones that use ".ogg" already, though.

**Comment by frtoli002** [comment]
Thanks so much for your reply. Could you step me through how to do that please? Where can I find those settings?

Thanks

**Comment by ohare93** [comment]
> Thanks so much for your reply. Could you step me through how to do that please? Where can I find those settings?

In Anki (Desktop, not mobile): Tools -> anki-forvo-dl -> Preferences -> Enable "skipOggFallback" in the bottom left

**Comment by frtoli002** [comment]
Thanks so much. Unfortunately I don’t seem to have that option. Or I’m being stupid. 

Should I maybe redownload the add on ?

**Comment by ohare93** [comment]
:man_shrugging: I have the latest version of the add-on: https://ankiweb.net/shared/info/858591644

Are you sure you have it enabled? Restart anki to be sure

**Comment by realmayus** [comment]
I tried adding a converter to the plugin, but this makes the plugin not portable anymore.... For now you'll have to manage with the skipOggFallback option I'm afraid :(
