### ISSUE TITLE
Forward slash in filenames not properly escaped

### ISSUE THREAD

**Issue by JohannesGaessler** [realmayus/anki_forvo_dl#61]
When trying to preview audio for the word "mon/ma" the following exception occurs:

Traceback (most recent call last):
  File "/home/johannesg/.local/share/Anki2/addons21/858591644/src/AddSingle.py", line 31, in play_audio
    pronunciation.download_pronunciation()  # Download audio on demand
  File "/home/johannesg/.local/share/Anki2/addons21/858591644/src/Forvo.py", line 40, in download_pronunciation
    with open(dl_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/johannesg/.local/share/Anki2/addons21/858591644/temp/pronunciation_fr_mon/ma.mp3'

I am using Linux where the forward slash instead of the backward slash is used for directories.
Any forward slash in a file name is apparently not properly escaped and instead interpreted as a directory.

**Comment by realmayus** [comment]
Thanks for the report! Should be fixed now.
