### ISSUE TITLE
The add-on suddenly stopped working

### ISSUE THREAD

**Issue by Expertium** [realmayus/anki_forvo_dl#64]
I'm using Anki 2.1.49, and everything worked just fine until yesterday. I did not update Anki, nor did I install any new add-ons. Downgrading to version 2.1.35 didn't help.
Here's the error message

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "aqt\editor.py", line 524, in <lambda>
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 217, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 130, in add_pronunciation
    results = forvo.get_pronunciations().pronunciations
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\src\Forvo.py", line 111, in get_pronunciations
    pronunciations: Tag = lang_container.find_all(class_="pronunciations")[0].find_all(class_="show-all-pronunciations")[0].find_all("li")
IndexError: list index out of range

**Comment by shialk** [comment]
Same here with:
Anki 2.1.54 (88e539aa) Python 3.10.5 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-07-14 13:12:17
Add-ons possibly involved: ⁨anki-forvo-dl - Forvo Pronunciation

**Comment by cjselbyspink** [comment]
Same.  As of today, both before and after updating to the latest Anki, the forvo plug in stopped working.  Was fine yesterday.  Presume change must be on forvo end if nothing else changed?  Same for my wife.

Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-14 15:06:12
Add-ons possibly involved: ⁨anki-forvo-dl - Forvo Pronunciation Downloader fully automatic⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 541, in handler
  File "aqt/editor.py", line 528, in <lambda>
  File "/Users/selby/Library/Application Support/Anki2/addons21/858591644/__init__.py", line 217, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "/Users/selby/Library/Application Support/Anki2/addons21/858591644/__init__.py", line 130, in add_pronunciation
    results = forvo.get_pronunciations().pronunciations
  File "/Users/selby/Library/Application Support/Anki2/addons21/858591644/src/Forvo.py", line 111, in get_pronunciations
    pronunciations: Tag = lang_container.find_all(class_="pronunciations")[0].find_all(class_="show-all-pronunciations")[0].find_all("li")
IndexError: list index out of range

**Comment by Calvin-Xu** [comment]
I have a badly hacked together fork of this plugin and made some minimal tweaking to get it working again after the Forvo site update. These changes should work for now:

In `Forvo.py`:
* line 111, change `pronunciations: Tag = lang_container.find_all(class_="pronunciations")[0].find_all(class_="show-all-pronunciations")[0].find_all("li")` to `pronunciations: Tag = lang_container.find_all(class_="pronunciations")[0].find_all(class_="pronunciations-list")[0].find_all("li")`
* line 149 to 150, change `int(pronunciation.find_all(class_="more")[0].find_all(class_="main_actions")[0].find_all(
                                  class_="share")[0].attrs["data-id"]),` to `int(pronunciation.find_all(class_="more")[0].find_all(class_="main_actions")[0].find_all(class_="vote_good")[0].attrs["data-p2"]),`

I won't open a pull request as I didn't really test this and the author might want to address this differently.

**Comment by Expertium** [comment]
That doesn't work for me, unfortunately. I'm still getting an error.

Caught exception:

Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "aqt\editor.py", line 524, in <lambda>
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 217, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 130, in add_pronunciation
    results = forvo.get_pronunciations().pronunciations
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\858591644\src\Forvo.py", line 142, in get_pronunciations
    username = re.findall("Pronunciation by(.*)", pronunciation.contents[2], re.S)[0].strip()
IndexError: list index out of range

**Comment by tomodutch** [comment]
These changes should probably be released to ankiweb as they fixed the issue for me

**Comment by aceamarco** [comment]
Have these changes been pushed to ankiweb? I'm still getting this issue.

**Comment by Expertium** [comment]
It seems like the above fix doesn't fully solve the problem. I still get an error sometimes, albeit rarely.

**Comment by Calvin-Xu** [comment]
> It seems like the above fix doesn't fully solve the problem. I still get an error sometimes, albeit rarely.

My fix wasn't very good and I recommend applying the changes from https://github.com/realmayus/anki_forvo_dl/pull/67, which tries to be smarter in figuring out the `data-id`.

> Have these changes been pushed to AnkiWeb?

No. Naturally only the author can push updates to AnkiWeb, and I think @realmayus was last active on this repo about 9 months ago. For now it is probably the best to apply these changes yourself.

(Tools - Addons - anki-forvo-dl - View Files, then replace Forvo.py with the version in https://github.com/realmayus/anki_forvo_dl/pull/67)

**Comment by aceamarco** [comment]
I see, thank you! I appreciate your responses :)

**Comment by realmayus** [comment]
Thanks everyone for the report and to @univerio for the PR! I just published the changes on Ankiweb and you should be able to update the plugin :)
