### ISSUE TITLE
anki-forvo-dl - Forvo Pronunciation Downloader (fully automatic) not working since last one week

### ISSUE THREAD

**Issue by engineer2012** [realmayus/anki_forvo_dl#74]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-21 15:47:48

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "aqt.editor", line 561, in <lambda>
  File "C:\Users\LENOVO\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 217, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "C:\Users\LENOVO\AppData\Roaming\Anki2\addons21\858591644\__init__.py", line 130, in add_pronunciation
    results = forvo.get_pronunciations().pronunciations
  File "C:\Users\LENOVO\AppData\Roaming\Anki2\addons21\858591644\src\Forvo.py", line 111, in get_pronunciations
    pronunciations: Tag = lang_container.find_all(class_="pronunciations")[0].find_all(class_="show-all-pronunciations")[0].find_all("li")
IndexError: list index out of range

**Comment by OltiP2** [comment]
its the same error for me too

**Comment by OltiP2** [comment]
This fixed it for me(found it under the comments on anki add on page)
"For everyone who is getting an error - use this: https://github.com/realmayus/anki_forvo_dl/blob/1148ee91fa803ad1b61508727c1862e025635be5/src/Forvo.py
In Anki, go to Tools -> Add-ons -> anki-forvo-dl - Forvo Pronunciation Downloader (fully automatic) -> View Files, then look for a folder called "src", you will find Forvo.py inside. Open it in Notepad++, delete all of the code and replace it with the code from the link above. Save, close Notepad++, close Anki, restart."

**Comment by Morpheus-Q** [comment]
It doesn't work for my anki, and I dont know why.


> This fixed it for me(found it under the comments on anki add on page) "For everyone who is getting an error - use this: https://github.com/realmayus/anki_forvo_dl/blob/1148ee91fa803ad1b61508727c1862e025635be5/src/Forvo.py In Anki, go to Tools -> Add-ons -> anki-forvo-dl - Forvo Pronunciation Downloader (fully automatic) -> View Files, then look for a folder called "src", you will find Forvo.py inside. Open it in Notepad++, delete all of the code and replace it with the code from the link above. Save, close Notepad++, close Anki, restart."

**Comment by realmayus** [comment]
Thanks everyone for reporting the issue and sorry for the long inactivity period. I just merged @univerio 's PR and added some other fixes for bugs introduced with the new anki version. Just uploaded everything to ankiweb, you should be able to download the update!
