### ISSUE TITLE
Add-on fails to load

### ISSUE THREAD

**Issue by SoakedTofu** [realmayus/anki_forvo_dl#78]
Hi, I'm having an issue with the new update. The add-on fails to load with the following error message:

> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
> 
> When loading '⁨anki-forvo-dl - Forvo Pronunciation Downloader fully automatic⁩':
> ⁨Traceback (most recent call last):
>   File "aqt.addons", line 244, in loadAddons
>   File "/home/user/.local/share/Anki2/addons21/858591644/__init__.py", line 15, in <module>
>     from .src.AddSingle import AddSingle
>   File "/home/user/.local/share/Anki2/addons21/858591644/src/AddSingle.py", line 8, in <module>
>     from .Forvo import Pronunciation
>   File "/home/user/.local/share/Anki2/addons21/858591644/src/Forvo.py", line 16, in <module>
>     from .util.Util import log_debug
>   File "/home/user/.local/share/Anki2/addons21/858591644/src/util/Util.py", line 10, in <module>
>     from anki_forvo_dl.src.Exceptions import FieldNotFoundException
> ModuleNotFoundError: No module named 'anki_forvo_dl'

Anki 2.1.54 qt6
Fedora 36

Thank you!

**Comment by realmayus** [comment]
Hey, could you try updating the addon? I fixed this issue earlier today.

**Comment by SoakedTofu** [comment]
Hi, everything works now fine after the update. Thanks a lot!
