### ISSUE TITLE
Doesn´t work for Spanish special symbols

### ISSUE THREAD

**Issue by dimkagabber** [realmayus/anki_forvo_dl#87]
Forvo has required phrase, but the plugin can´t find it

![image](https://user-images.githubusercontent.com/36014406/194780833-fa181472-5df7-4d7f-97cc-480c002f49c7.png)
![image](https://user-images.githubusercontent.com/36014406/194780841-4cf1a284-f752-41db-b7d1-86cc8b6a72b4.png)

**Comment by dimkagabber** [comment]
in other cases the plugin works nicely

**Comment by StanBoots** [comment]
Just a guess but this may be related to the issue "Not working if a sentence has a question mark #88".  

I could never get a sound file for any sentence that ends in a question mark.

Otherwise, add-on works great!

**Comment by realmayus** [comment]
Fixed by https://github.com/realmayus/anki_forvo_dl/commit/424db9ea5fe97c53b24769b31b9bd4dc90176154
