### ISSUE TITLE
Not working if a sentence has a question mark

### ISSUE THREAD

**Issue by StanBoots** [realmayus/anki_forvo_dl#88]
Thanks for this add-on.  I've been using it to get sentences from the Vietnamese Useful Travel Phrases.

I've noticed the following using Windows 10, Anki Version ⁨2.1.54, Qt 5:

1) Working great - For all declaratory sentences, Forvo has no period "." at the end of the sentence.  In all these instances, the add-on works great.  It displays all the available pronunciations.  I've successfully downloaded 62 sound files.

2) Not working - For all the interrogatory sentences, Forvo has a question mark "?" at the end of the sentence.  The add-on never finds a sound file (No results) when there is a question mark in the sentence, even though the sound files are on the Forvo web page. I've tested that 65 times.

To elaborate on that - I realize that Windows doesn't allow a question mark in a filename.  But I don't think that's the problem here.  The mp3 sound file can be directly downloaded from the Forvo web page (after logging in with a free Forvo account).  That mp3 sound file doesn't have a question mark at the end (it ends with "_" character).  However, it seems like the add-on should be able to find the file and download just like any other sound file.

In summary, add-on always works with sentences that have no ending punctuation, but never works with an ending question mark.

Thanks for the work on the add-on.  It's useful for anything that doesn't end in a question mark.  I particularly like the ability to listen to all the available choices and select the sound file I like best.  

*************************************************************************

Update - I directly downloaded dozens of files from Forvo with a question mark and added to Anki manually.

I noticed something to further demonstrate that sentences with a question mark can't be found by the add-on.  Note I have tried with and without excluding "?" in the add-on preferences.  It doesn't make a difference.

The add-on did find a sound file for one question in Forvo

Search directly in Forvo for "Bạn đến từ đâu?"  Forvo found four pronunciations
Forvo found these three pronunciations. Notice the question mark.
	Bạn đến từ đâu?
	Bạn đến từ đâu?
	Bạn đến từ đâu?

Forvo also found this one pronunciation. Notice the lowercase 'b' and no question mark.
	bạn đến từ đâu

The add-on did discover and could download the one sentence without the question mark.  But it didn't find any of the other three pronuciations.  The lowercase letter was not the problem.  I've tested uppercase and lowercase letters. Both Forvo and the add-on will find matches OK.

Observation:  If there is a question mark in the sentence, this add-on won't discover the sound file.   If there is no question mark, the add-on will find the sound file.

**Comment by realmayus** [comment]
Fixed by https://github.com/realmayus/anki_forvo_dl/commit/424db9ea5fe97c53b24769b31b9bd4dc90176154
