### ISSUE TITLE
'No results found' for any request

### ISSUE THREAD

**Issue by homocomputeris** [realmayus/anki_forvo_dl#89]
Since 4 Nov any search returns 'No results found'. How can I check where is the problem?

**Comment by HellZDarkArkon** [comment]
Same thing happens to me.  I really like this addon too, since i didnt need to re-signin to forvo every 6 minutes to get my pronunciations.

**Comment by miwucs** [comment]
Forvo now returns a 403 Forbidden error for the requests sent by the addon.
You can see it with curl too: `curl -v https://forvo.com/word/test`
In the output you can see `HTTP/2 403` and the HTML is a page that says "forvo.com needs to review the security of your connection before proceeding"

**Comment by miwucs** [comment]
I am not the dev but I expect this will be difficult to fix :( Forvo basically disabled the way the addon was downloading audio. It's not entirely impossible to bypass the bot detection but it's difficult and presumably against ToS. The proper fix would be to use the official API but you have to pay for it https://api.forvo.com/ (cheapest plan is $2/month)

As an alternative there is this "half-automatic" addon https://ankiweb.net/shared/info/1407979740 which is a bit more work to use as the name implies, but it only requires a free forvo account.

**Comment by realmayus** [comment]
Thanks for the report. I'm considering ditching the original backend and adding something that interfaces with its paid API

**Comment by homocomputeris** [comment]
Cloudflare says https://api.forvo.com/plans-and-pricing/ is down, so maybe it's a temporary issue on the Forvo's side

**Comment by homocomputeris** [comment]
Maybe https://lingualibre.org/ can be used as an alternative source.

**Comment by HellZDarkArkon** [comment]
just suddenly started working for me again. dunno why.

**Comment by miwucs** [comment]
Indeed it works for me again as well. And the api.forvo.com pages are back up too, so as @homocomputeris said it might have been a temporary outage (which is weird since it looked more like a feature than an outage, but hey it's good news).
