### ISSUE TITLE
Basic (type in the answer cards)

### ISSUE THREAD

**Issue by Jacob-Weather** [realmayus/anki_forvo_dl#9]
I learn languages on Anki and I put English on the Front with the French on the Back.

Where should I insert the forvo pronunciation so that I do not hear it with the English but after I have attempted the French word.

**Comment by realmayus** [comment]
That depends on your note type. You can create a field for the audio, or you can just select the field that is on the back, which would be French for you 😉

**Comment by Jacob-Weather** [comment]
I have tried to put the Forvo file inside the 'back' field but it doesn't seem to play, not even when I create a new field specifically for it. It may have something to do with me using a 'type in the answer' note type.

**Comment by realmayus** [comment]
Could you try to press 'R' when reviewing the card?  Maybe you haven't enabled the setting for automatically playing the audio files 🤔

**Comment by Jacob-Weather** [comment]
That doesn't seem to work either but I have come up with a different solution. Thanks for your help

**Comment by realmayus** [comment]
Nice! Have fun :D
