### ISSUE TITLE
suggestion: Don't block UI thread during API requests

### ISSUE THREAD

**Issue by louis-vs** [realmayus/anki_forvo_dl#93]
Firstly, thank you for the add-on! It's clearly taken a lot of work to produce and maintain, and I've found it invaluable for building vocab decks. My suggestion is as follows:

Currently, the add-on blocks the UI thread while making API calls (searching & downloading). This causes Anki to freeze, potentially for a long time if you have a slow connection. This frozen state can only be broken when the request completes or by force-quitting the program.

I know nothing about Anki add-on development so I don't know if this is possible, but it would be better for those on slow connections if requests were performed asynchronously. Some kind of loading indicator showing that a request is in process would be necessary.

**Comment by realmayus** [comment]
Fixed by https://github.com/realmayus/anki_forvo_dl/commit/c96c30cc7d7712d4232bff3a995aa09f51a00e26
