### ISSUE TITLE
Issue with filename

### ISSUE THREAD

**Issue by christianniebling** [realmayus/anki_forvo_dl#95]
Observed on windows (possibly issue specific to windows) 
Using anki Version ⁨2.1.65 (aa9a734f)⁩

After selecting sound to download, the `Audio` field in the card is populated with the `[sound:<filename>.<ext>]` information, However, anki cannot play the sound, even though the spelling of the filename + extension is correct.

On my machine, if you add a space to the end of the `Audio` string, the sound file can then be played.

Its like there is a hidden character at the end of the string thats messing it up. (Carriage return?)

**Comment by realmayus** [comment]
Should be fixed by https://github.com/realmayus/anki_forvo_dl/commit/5c1fbf8f26694abfeb9b11f345c41c2331f87485. Please reopen if issue still occurs.
